export declare type CSS = Merge<{
	"-webkit-line-clamp": "none" | number;
	// TODO
	"-webkit-text-fill-color": any;
	// TODO
	"-webkit-text-stroke": any;
	// TODO
	"-webkit-text-stroke-color": any;
	// TODO
	"-webkit-text-stroke-width": any;
	// TODO
	"accent-color": any;
	// TODO
	"align-content": any;
	// TODO
	"align-items": any;
	// TODO
	"align-self": any;
	// TODO
	"align-tracks": any;
	// TODO
	"all": any;
	// TODO
	"animation": any;
	// TODO
	"animation-composition": any;
	// TODO
	"animation-delay": any;
	// TODO
	"animation-direction": any;
	// TODO
	"animation-duration": any;
	// TODO
	"animation-fill-mode": any;
	// TODO
	"animation-iteration-count": any;
	// TODO
	"animation-name": any;
	// TODO
	"animation-play-state": any;
	// TODO
	"animation-timeline": any;
	// TODO
	"animation-timing-function": any;
	// TODO
	"appearance": any;
	// TODO
	"aspect-ratio": any;
	// TODO
	"backdrop-filter": any;
	// TODO
	"backface-visibility": any;
	// TODO
	"background": any;
	// TODO
	"background-attachment": any;
	// TODO
	"background-blend-mode": any;
	// TODO
	"background-clip": any;
	// TODO
	"background-color": any;
	// TODO
	"background-image": any;
	// TODO
	"background-origin": any;
	// TODO
	"background-position": any;
	// TODO
	"background-position-x": any;
	// TODO
	"background-position-y": any;
	// TODO
	"background-repeat": any;
	// TODO
	"background-size": any;
	// TODO
	"block-size": any;
	// TODO
	"border": any;
	// TODO
	"border-block": any;
	// TODO
	"border-block-color": any;
	// TODO
	"border-block-end": any;
	// TODO
	"border-block-end-color": any;
	// TODO
	"border-block-end-style": any;
	// TODO
	"border-block-end-width": any;
	// TODO
	"border-block-start": any;
	// TODO
	"border-block-start-color": any;
	// TODO
	"border-block-start-style": any;
	// TODO
	"border-block-start-width": any;
	// TODO
	"border-block-style": any;
	// TODO
	"border-block-width": any;
	// TODO
	"border-bottom": any;
	// TODO
	"border-bottom-color": any;
	// TODO
	"border-bottom-left-radius": any;
	// TODO
	"border-bottom-right-radius": any;
	// TODO
	"border-bottom-style": any;
	// TODO
	"border-bottom-width": any;
	// TODO
	"border-collapse": any;
	// TODO
	"border-color": any;
	// TODO
	"border-end-end-radius": any;
	// TODO
	"border-end-start-radius": any;
	// TODO
	"border-image": any;
	// TODO
	"border-image-outset": any;
	// TODO
	"border-image-repeat": any;
	// TODO
	"border-image-slice": any;
	// TODO
	"border-image-source": any;
	// TODO
	"border-image-width": any;
	// TODO
	"border-inline": any;
	// TODO
	"border-inline-color": any;
	// TODO
	"border-inline-end": any;
	// TODO
	"border-inline-end-color": any;
	// TODO
	"border-inline-end-style": any;
	// TODO
	"border-inline-end-width": any;
	// TODO
	"border-inline-start": any;
	// TODO
	"border-inline-start-color": any;
	// TODO
	"border-inline-start-style": any;
	// TODO
	"border-inline-start-width": any;
	// TODO
	"border-inline-style": any;
	// TODO
	"border-inline-width": any;
	// TODO
	"border-left": any;
	// TODO
	"border-left-color": any;
	// TODO
	"border-left-style": any;
	// TODO
	"border-left-width": any;
	// TODO
	"border-radius": any;
	// TODO
	"border-right": any;
	// TODO
	"border-right-color": any;
	// TODO
	"border-right-style": any;
	// TODO
	"border-right-width": any;
	// TODO
	"border-spacing": any;
	// TODO
	"border-start-end-radius": any;
	// TODO
	"border-start-start-radius": any;
	// TODO
	"border-style": any;
	// TODO
	"border-top": any;
	// TODO
	"border-top-color": any;
	// TODO
	"border-top-left-radius": any;
	// TODO
	"border-top-right-radius": any;
	// TODO
	"border-top-style": any;
	// TODO
	"border-top-width": any;
	// TODO
	"border-width": any;
	// TODO
	"bottom": any;
	// TODO
	"box-decoration-break": any;
	// TODO
	"box-shadow": any;
	// TODO
	"box-sizing": any;
	// TODO
	"break-after": any;
	// TODO
	"break-before": any;
	// TODO
	"break-inside": any;
	// TODO
	"caption-side": any;
	// TODO
	"caret-color": any;
	// TODO
	"clear": any;
	// TODO
	"clip": any;
	// TODO
	"clip-path": any;
	// TODO
	"color": any;
	// TODO
	"color-scheme": any;
	// TODO
	"column-count": any;
	// TODO
	"column-fill": any;
	// TODO
	"column-gap": any;
	// TODO
	"column-rule": any;
	// TODO
	"column-rule-color": any;
	// TODO
	"column-rule-style": any;
	// TODO
	"column-rule-width": any;
	// TODO
	"column-span": any;
	// TODO
	"column-width": any;
	// TODO
	"columns": any;
	// TODO
	"contain": any;
	// TODO
	"contain-intrinsic-block-size": any;
	// TODO
	"contain-intrinsic-height": any;
	// TODO
	"contain-intrinsic-inline-size": any;
	// TODO
	"contain-intrinsic-size": any;
	// TODO
	"contain-intrinsic-width": any;
	// TODO
	"content": any;
	// TODO
	"content-visibility": any;
	// TODO
	"counter-increment": any;
	// TODO
	"counter-reset": any;
	// TODO
	"counter-set": any;
	// TODO
	"cursor": any;
	// TODO
	"direction": any;
	// TODO
	"display": any;
	// TODO
	"empty-cells": any;
	// TODO
	"filter": any;
	// TODO
	"flex": any;
	// TODO
	"flex-basis": any;
	// TODO
	"flex-direction": any;
	// TODO
	"flex-flow": any;
	// TODO
	"flex-grow": any;
	// TODO
	"flex-shrink": any;
	// TODO
	"flex-wrap": any;
	// TODO
	"float": any;
	// TODO
	"font": any;
	// TODO
	"font-family": any;
	// TODO
	"font-feature-settings": any;
	// TODO
	"font-kerning": any;
	// TODO
	"font-language-override": any;
	// TODO
	"font-optical-sizing": any;
	// TODO
	"font-size": any;
	// TODO
	"font-size-adjust": any;
	// TODO
	"font-stretch": any;
	// TODO
	"font-style": any;
	// TODO
	"font-synthesis": any;
	// TODO
	"font-variant": any;
	// TODO
	"font-variant-alternates": any;
	// TODO
	"font-variant-caps": any;
	// TODO
	"font-variant-east-asian": any;
	// TODO
	"font-variant-ligatures": any;
	// TODO
	"font-variant-numeric": any;
	// TODO
	"font-variant-position": any;
	// TODO
	"font-variation-settings": any;
	// TODO
	"font-weight": any;
	// TODO
	"forced-color-adjust": any;
	// TODO
	"gap": any;
	// TODO
	"grid": any;
	// TODO
	"grid-area": any;
	// TODO
	"grid-auto-columns": any;
	// TODO
	"grid-auto-flow": any;
	// TODO
	"grid-auto-rows": any;
	// TODO
	"grid-column": any;
	// TODO
	"grid-column-end": any;
	// TODO
	"grid-column-start": any;
	// TODO
	"grid-row": any;
	// TODO
	"grid-row-end": any;
	// TODO
	"grid-row-start": any;
	// TODO
	"grid-template": any;
	// TODO
	"grid-template-areas": any;
	// TODO
	"grid-template-columns": any;
	// TODO
	"grid-template-rows": any;
	// TODO
	"hanging-punctuation": any;
	// TODO
	"height": any;
	// TODO
	"hyphenate-character": any;
	// TODO
	"hyphens": any;
	// TODO
	"image-orientation": any;
	// TODO
	"image-rendering": any;
	// TODO
	"image-resolution": any;
	// TODO
	"ime-mode": any;
	// TODO
	"initial-letter": any;
	// TODO
	"initial-letter-align": any;
	// TODO
	"inline-size": any;
	// TODO
	"inset": any;
	// TODO
	"inset-block": any;
	// TODO
	"inset-block-end": any;
	// TODO
	"inset-block-start": any;
	// TODO
	"inset-inline": any;
	// TODO
	"inset-inline-end": any;
	// TODO
	"inset-inline-start": any;
	// TODO
	"isolation": any;
	// TODO
	"justify-content": any;
	// TODO
	"justify-items": any;
	// TODO
	"justify-self": any;
	// TODO
	"justify-tracks": any;
	// TODO
	"left": any;
	// TODO
	"letter-spacing": any;
	// TODO
	"line-break": any;
	// TODO
	"line-height": any;
	// TODO
	"line-height-step": any;
	// TODO
	"list-style": any;
	// TODO
	"list-style-image": any;
	// TODO
	"list-style-position": any;
	// TODO
	"list-style-type": any;
	// TODO
	"margin": any;
	// TODO
	"margin-block": any;
	// TODO
	"margin-block-end": any;
	// TODO
	"margin-block-start": any;
	// TODO
	"margin-bottom": any;
	// TODO
	"margin-inline": any;
	// TODO
	"margin-inline-end": any;
	// TODO
	"margin-inline-start": any;
	// TODO
	"margin-left": any;
	// TODO
	"margin-right": any;
	// TODO
	"margin-top": any;
	// TODO
	"margin-trim": any;
	// TODO
	"mask": any;
	// TODO
	"mask-border": any;
	// TODO
	"mask-border-mode": any;
	// TODO
	"mask-border-outset": any;
	// TODO
	"mask-border-repeat": any;
	// TODO
	"mask-border-slice": any;
	// TODO
	"mask-border-source": any;
	// TODO
	"mask-border-width": any;
	// TODO
	"mask-clip": any;
	// TODO
	"mask-composite": any;
	// TODO
	"mask-image": any;
	// TODO
	"mask-mode": any;
	// TODO
	"mask-origin": any;
	// TODO
	"mask-position": any;
	// TODO
	"mask-repeat": any;
	// TODO
	"mask-size": any;
	// TODO
	"mask-type": any;
	// TODO
	"masonry-auto-flow": any;
	// TODO
	"math-depth": any;
	// TODO
	"math-shift": any;
	// TODO
	"math-style": any;
	// TODO
	"max-block-size": any;
	// TODO
	"max-height": any;
	// TODO
	"max-inline-size": any;
	// TODO
	"max-width": any;
	// TODO
	"min-block-size": any;
	// TODO
	"min-height": any;
	// TODO
	"min-inline-size": any;
	// TODO
	"min-width": any;
	// TODO
	"mix-blend-mode": any;
	// TODO
	"object-fit": any;
	// TODO
	"object-position": any;
	// TODO
	"offset": any;
	// TODO
	"offset-anchor": any;
	// TODO
	"offset-distance": any;
	// TODO
	"offset-path": any;
	// TODO
	"offset-position": any;
	// TODO
	"offset-rotate": any;
	// TODO
	"opacity": any;
	// TODO
	"order": any;
	// TODO
	"orphans": any;
	// TODO
	"outline": any;
	// TODO
	"outline-color": any;
	// TODO
	"outline-offset": any;
	// TODO
	"outline-style": any;
	// TODO
	"outline-width": any;
	// TODO
	"overflow": any;
	// TODO
	"overflow-anchor": any;
	// TODO
	"overflow-block": any;
	// TODO
	"overflow-clip-margin": any;
	// TODO
	"overflow-inline": any;
	// TODO
	"overflow-wrap": any;
	// TODO
	"overflow-x": any;
	// TODO
	"overflow-y": any;
	// TODO
	"overscroll-behavior": any;
	// TODO
	"overscroll-behavior-block": any;
	// TODO
	"overscroll-behavior-inline": any;
	// TODO
	"overscroll-behavior-x": any;
	// TODO
	"overscroll-behavior-y": any;
	// TODO
	"padding": any;
	// TODO
	"padding-block": any;
	// TODO
	"padding-block-end": any;
	// TODO
	"padding-block-start": any;
	// TODO
	"padding-bottom": any;
	// TODO
	"padding-inline": any;
	// TODO
	"padding-inline-end": any;
	// TODO
	"padding-inline-start": any;
	// TODO
	"padding-left": any;
	// TODO
	"padding-right": any;
	// TODO
	"padding-top": any;
	// TODO
	"page-break-after": any;
	// TODO
	"page-break-before": any;
	// TODO
	"page-break-inside": any;
	// TODO
	"paint-order": any;
	// TODO
	"perspective": any;
	// TODO
	"perspective-origin": any;
	// TODO
	"place-content": any;
	// TODO
	"place-items": any;
	// TODO
	"place-self": any;
	// TODO
	"pointer-events": any;
	// TODO
	"position": any;
	// TODO
	"print-color-adjust": any;
	// TODO
	"quotes": any;
	// TODO
	"resize": any;
	// TODO
	"right": any;
	// TODO
	"rotate": any;
	// TODO
	"row-gap": any;
	// TODO
	"ruby-align": any;
	// TODO
	"ruby-position": any;
	// TODO
	"scale": any;
	// TODO
	"scroll-behavior": any;
	// TODO
	"scroll-margin": any;
	// TODO
	"scroll-margin-block": any;
	// TODO
	"scroll-margin-block-end": any;
	// TODO
	"scroll-margin-block-start": any;
	// TODO
	"scroll-margin-bottom": any;
	// TODO
	"scroll-margin-inline": any;
	// TODO
	"scroll-margin-inline-end": any;
	// TODO
	"scroll-margin-inline-start": any;
	// TODO
	"scroll-margin-left": any;
	// TODO
	"scroll-margin-right": any;
	// TODO
	"scroll-margin-top": any;
	// TODO
	"scroll-padding": any;
	// TODO
	"scroll-padding-block": any;
	// TODO
	"scroll-padding-block-end": any;
	// TODO
	"scroll-padding-block-start": any;
	// TODO
	"scroll-padding-bottom": any;
	// TODO
	"scroll-padding-inline": any;
	// TODO
	"scroll-padding-inline-end": any;
	// TODO
	"scroll-padding-inline-start": any;
	// TODO
	"scroll-padding-left": any;
	// TODO
	"scroll-padding-right": any;
	// TODO
	"scroll-padding-top": any;
	// TODO
	"scroll-snap-align": any;
	// TODO
	"scroll-snap-stop": any;
	// TODO
	"scroll-snap-type": any;
	// TODO
	"scroll-timeline": any;
	// TODO
	"scroll-timeline-axis": any;
	// TODO
	"scroll-timeline-name": any;
	// TODO
	"scrollbar-color": any;
	// TODO
	"scrollbar-gutter": any;
	// TODO
	"scrollbar-width": any;
	// TODO
	"shape-image-threshold": any;
	// TODO
	"shape-margin": any;
	// TODO
	"shape-outside": any;
	// TODO
	"tab-size": any;
	// TODO
	"table-layout": any;
	// TODO
	"text-align": any;
	// TODO
	"text-align-last": any;
	// TODO
	"text-combine-upright": any;
	// TODO
	"text-decoration": any;
	// TODO
	"text-decoration-color": any;
	// TODO
	"text-decoration-line": any;
	// TODO
	"text-decoration-skip": any;
	// TODO
	"text-decoration-skip-ink": any;
	// TODO
	"text-decoration-style": any;
	// TODO
	"text-decoration-thickness": any;
	// TODO
	"text-emphasis": any;
	// TODO
	"text-emphasis-color": any;
	// TODO
	"text-emphasis-position": any;
	// TODO
	"text-emphasis-style": any;
	// TODO
	"text-indent": any;
	// TODO
	"text-justify": any;
	// TODO
	"text-orientation": any;
	// TODO
	"text-overflow": any;
	// TODO
	"text-rendering": any;
	// TODO
	"text-shadow": any;
	// TODO
	"text-size-adjust": any;
	// TODO
	"text-transform": any;
	// TODO
	"text-underline-offset": any;
	// TODO
	"text-underline-position": any;
	// TODO
	"top": any;
	// TODO
	"touch-action": any;
	// TODO
	"transform": any;
	// TODO
	"transform-box": any;
	// TODO
	"transform-origin": any;
	// TODO
	"transform-style": any;
	// TODO
	"transition": any;
	// TODO
	"transition-delay": any;
	// TODO
	"transition-duration": any;
	// TODO
	"transition-property": any;
	// TODO
	"transition-timing-function": any;
	// TODO
	"translate": any;
	// TODO
	"unicode-bidi": any;
	// TODO
	"user-select": any;
	// TODO
	"vertical-align": any;
	// TODO
	"visibility": any;
	// TODO
	"white-space": any;
	// TODO
	"widows": any;
	// TODO
	"width": any;
	// TODO
	"will-change": any;
	// TODO
	"word-break": any;
	// TODO
	"word-spacing": any;
	// TODO
	"writing-mode": any;
	// TODO
	"z-index": any;
}, GlobalValue>;

declare type GlobalValue = "inherit" | "initial" | "unset";

// https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
declare type TypeAlpha = number | TypePercentage;
declare type TypeAngle = `${number}${"deg" | "grad" | "rad" | "turn" | "%"}`;
declare type TypeBasicShape = `${"inset" | "circle" | "ellipse" | "polygon" | "path"}(${string})`; // TODO
declare type TypeBlendMode = "normal" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "color-dodge" | "color-burn" | "hard-light" | "soft-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity";
declare type TypeColor = number | TypeHexColor | `${"rgb" | "rgba" | "hsl" | "hsla" | "hwb" | "lab" | "lch" | "oklab" | "oklch" | "color"}(${string})`; // TODO
declare type TypeFunction = any; // TODO
// TODO
declare type TypeDisplayBox = any;
// TODO
declare type TypeDisplayInside = any;
// TODO
declare type TypeDisplayInternal = any;
// TODO
declare type TypeDisplayLegacy = any;
// TODO
declare type TypeDisplayListitem = any;
// TODO
declare type TypeDisplayOutside = any;
// TODO
declare type TypeEasingFunction = any;
// TODO
declare type TypeFilterFunction = `${"blur" | "brightness" | "contrast" | "drop-shadow" | "grayscale" | "hue-rotate" | "invert" | "opacity" | "sepia" | "saturate"}(${string})`; // TODO
// TODO
declare type TypeFlex = any;
declare type TypeFrequency = `${number}${"Hz" | "kHz" | "%"}`;
// TODO
declare type TypeGradient = any;
declare type TypeHexColor = `#${string}`;
// TODO
declare type TypeImage = any;
declare type TypeLength = `${number}${"cap" | "ch" | "em" | "ex" | "ic" | "lh" | "rem" | "rlh" | "vh" | "vw" | "vi" | "vb" | "vmin" | "vmax" | "px" | "cm" | "mm" | "Q" | "in" | "pc" | "pt" | "%"}`;
declare type TypeNamedColor = "black" | "silver" | "gray" | "white" | "maroon" | "red" | "purple" | "fuchsia" | "green" | "lime" | "olive" | "yellow" | "navy" | "blue" | "teal" | "aqua" | "orange" | "aliceblue" | "antiquewhite" | "aquamarine" | "azure" | "beige" | "bisque" | "blanchedalmond" | "blueviolet" | "brown" | "burlywood" | "cadetblue" | "chartreuse" | "chocolate" | "coral" | "cornflowerblue" | "cornsilk" | "crimson" | "cyan" | "darkblue" | "darkcyan" | "darkgoldenrod" | "darkgray" | "darkgreen" | "darkgrey" | "darkkhaki" | "darkmagenta" | "darkolivegreen" | "darkorange" | "darkorchid" | "darkred" | "darksalmon" | "darkseagreen" | "darkslateblue" | "darkslategray" | "darkslategrey" | "darkturquoise" | "darkviolet" | "deeppink" | "deepskyblue" | "dimgray" | "dimgrey" | "dodgerblue" | "firebrick" | "floralwhite" | "forestgreen" | "gainsboro" | "ghostwhite" | "gold" | "goldenrod" | "greenyellow" | "grey" | "honeydew" | "hotpink" | "indianred" | "indigo" | "ivory" | "khaki" | "lavender" | "lavenderblush" | "lawngreen" | "lemonchiffon" | "lightblue" | "lightcoral" | "lightcyan" | "lightgoldenrodyellow" | "lightgray" | "lightgreen" | "lightgrey" | "lightpink" | "lightsalmon" | "lightseagreen" | "lightskyblue" | "lightslategray" | "lightslategrey" | "lightsteelblue" | "lightyellow" | "limegreen" | "linen" | "magenta" | "mediumaquamarine" | "mediumblue" | "mediumorchid" | "mediumpurple" | "mediumseagreen" | "mediumslateblue" | "mediumspringgreen" | "mediumturquoise" | "mediumvioletred" | "midnightblue" | "mintcream" | "mistyrose" | "moccasin" | "navajowhite" | "oldlace" | "olivedrab" | "orangered" | "orchid" | "palegoldenrod" | "palegreen" | "paleturquoise" | "palevioletred" | "papayawhip" | "peachpuff" | "peru" | "pink" | "plum" | "powderblue" | "rosybrown" | "royalblue" | "saddlebrown" | "salmon" | "sandybrown" | "seagreen" | "seashell" | "sienna" | "skyblue" | "slateblue" | "slategray" | "slategrey" | "snow" | "springgreen" | "steelblue" | "tan" | "thistle" | "tomato" | "transparent" | "turquoise" | "violet" | "wheat" | "whitesmoke" | "yellowgreen" | "rebeccapurple" | "transparent";
declare type TypePercentage = `${number}%`;
// TODO
declare type TypePosition = any;
declare type TypeRatio = `${number}/${number}`;
declare type TypeResolution = `${number}${"dpi" | "dpcm" | "dppx" | "x"}`;
declare type TypeShape = `rect(${string})`; // TODO
declare type TypeTime = `${number}${"s" | "ms" | "%"}`;
// TODO
declare type TypeTransformFunction = any;
// TODO
declare type TypeTranslationValue = any;

declare type Merge<T extends object, U> = {
	[K in keyof T]: T[K] | U;
}
