// TODO: Replace arrays with union joining inferring
export declare module css {

	export type Properties = {
		"webkitLineClamp": RealProperties["-webkit-line-clamp"];
		"webkitTextFillColor": RealProperties["-webkit-text-fill-color"];
		"webkitTextStroke": RealProperties["-webkit-text-stroke"];
		"webkitTextStrokeColor": RealProperties["-webkit-text-stroke-color"];
		"webkitTextStrokeWidth": RealProperties["-webkit-text-stroke-width"];
		"accentColor": RealProperties["accent-color"];
		"alignContent": RealProperties["align-content"];
		"alignItems": RealProperties["align-items"];
		"alignSelf": RealProperties["align-self"];
		"alignTracks": RealProperties["align-tracks"];
		"all": RealProperties["all"];
		"animation": RealProperties["animation"];
		"animationComposition": RealProperties["animation-composition"];
		"animationDelay": RealProperties["animation-delay"];
		"animationDirection": RealProperties["animation-direction"];
		"animationDuration": RealProperties["animation-duration"];
		"animationFillMode": RealProperties["animation-fill-mode"];
		"animationIterationCount": RealProperties["animation-iteration-count"];
		"animationName": RealProperties["animation-name"];
		"animationPlayState": RealProperties["animation-play-state"];
		"animationTimeline": RealProperties["animation-timeline"];
		"animationTimingFunction": RealProperties["animation-timing-function"];
		"appearance": RealProperties["appearance"];
		"aspectRatio": RealProperties["aspect-ratio"];
		"backdropFilter": RealProperties["backdrop-filter"];
		"backfaceVisibility": RealProperties["backface-visibility"];
		"background": RealProperties["background"];
		"backgroundAttachment": RealProperties["background-attachment"];
		"backgroundBlendMode": RealProperties["background-blend-mode"];
		"backgroundClip": RealProperties["background-clip"];
		"backgroundColor": RealProperties["background-color"];
		"backgroundImage": RealProperties["background-image"];
		"backgroundOrigin": RealProperties["background-origin"];
		"backgroundPosition": RealProperties["background-position"];
		"backgroundPositionX": RealProperties["background-position-x"];
		"backgroundPositionY": RealProperties["background-position-y"];
		"backgroundRepeat": RealProperties["background-repeat"];
		"backgroundSize": RealProperties["background-size"];
		"blockSize": RealProperties["block-size"];
		"border": RealProperties["border"];
		"borderBlock": RealProperties["border-block"];
		"borderBlockColor": RealProperties["border-block-color"];
		"borderBlockEnd": RealProperties["border-block-end"];
		"borderBlockEndColor": RealProperties["border-block-end-color"];
		"borderBlockEndStyle": RealProperties["border-block-end-style"];
		"borderBlockEndWidth": RealProperties["border-block-end-width"];
		"borderBlockStart": RealProperties["border-block-start"];
		"borderBlockStartColor": RealProperties["border-block-start-color"];
		"borderBlockStartStyle": RealProperties["border-block-start-style"];
		"borderBlockStartWidth": RealProperties["border-block-start-width"];
		"borderBlockStyle": RealProperties["border-block-style"];
		"borderBlockWidth": RealProperties["border-block-width"];
		"borderBottom": RealProperties["border-bottom"];
		"borderBottomColor": RealProperties["border-bottom-color"];
		"borderBottomLeftRadius": RealProperties["border-bottom-left-radius"];
		"borderBottomRightRadius": RealProperties["border-bottom-right-radius"];
		"borderBottomStyle": RealProperties["border-bottom-style"];
		"borderBottomWidth": RealProperties["border-bottom-width"];
		"borderCollapse": RealProperties["border-collapse"];
		"borderColor": RealProperties["border-color"];
		"borderEndEndRadius": RealProperties["border-end-end-radius"];
		"borderEndStartRadius": RealProperties["border-end-start-radius"];
		"borderImage": RealProperties["border-image"];
		"borderImageOutset": RealProperties["border-image-outset"];
		"borderImageRepeat": RealProperties["border-image-repeat"];
		"borderImageSlice": RealProperties["border-image-slice"];
		"borderImageSource": RealProperties["border-image-source"];
		"borderImageWidth": RealProperties["border-image-width"];
		"borderInline": RealProperties["border-inline"];
		"borderInlineColor": RealProperties["border-inline-color"];
		"borderInlineEnd": RealProperties["border-inline-end"];
		"borderInlineEndColor": RealProperties["border-inline-end-color"];
		"borderInlineEndStyle": RealProperties["border-inline-end-style"];
		"borderInlineEndWidth": RealProperties["border-inline-end-width"];
		"borderInlineStart": RealProperties["border-inline-start"];
		"borderInlineStartColor": RealProperties["border-inline-start-color"];
		"borderInlineStartStyle": RealProperties["border-inline-start-style"];
		"borderInlineStartWidth": RealProperties["border-inline-start-width"];
		"borderInlineStyle": RealProperties["border-inline-style"];
		"borderInlineWidth": RealProperties["border-inline-width"];
		"borderLeft": RealProperties["border-left"];
		"borderLeftColor": RealProperties["border-left-color"];
		"borderLeftStyle": RealProperties["border-left-style"];
		"borderLeftWidth": RealProperties["border-left-width"];
		"borderRadius": RealProperties["border-radius"];
		"borderRight": RealProperties["border-right"];
		"borderRightColor": RealProperties["border-right-color"];
		"borderRightStyle": RealProperties["border-right-style"];
		"borderRightWidth": RealProperties["border-right-width"];
		"borderSpacing": RealProperties["border-spacing"];
		"borderStartEndRadius": RealProperties["border-start-end-radius"];
		"borderStartStartRadius": RealProperties["border-start-start-radius"];
		"borderStyle": RealProperties["border-style"];
		"borderTop": RealProperties["border-top"];
		"borderTopColor": RealProperties["border-top-color"];
		"borderTopLeftRadius": RealProperties["border-top-left-radius"];
		"borderTopRightRadius": RealProperties["border-top-right-radius"];
		"borderTopStyle": RealProperties["border-top-style"];
		"borderTopWidth": RealProperties["border-top-width"];
		"borderWidth": RealProperties["border-width"];
		"bottom": RealProperties["bottom"];
		"boxDecorationBreak": RealProperties["box-decoration-break"];
		"boxShadow": RealProperties["box-shadow"];
		"boxSizing": RealProperties["box-sizing"];
		"breakAfter": RealProperties["break-after"];
		"breakBefore": RealProperties["break-before"];
		"breakInside": RealProperties["break-inside"];
		"captionSide": RealProperties["caption-side"];
		"caretColor": RealProperties["caret-color"];
		"clear": RealProperties["clear"];
		"clip": RealProperties["clip"];
		"clipPath": RealProperties["clip-path"];
		"color": RealProperties["color"];
		"colorScheme": RealProperties["color-scheme"];
		"columnCount": RealProperties["column-count"];
		"columnFill": RealProperties["column-fill"];
		"columnGap": RealProperties["column-gap"];
		"columnRule": RealProperties["column-rule"];
		"columnRuleColor": RealProperties["column-rule-color"];
		"columnRuleStyle": RealProperties["column-rule-style"];
		"columnRuleWidth": RealProperties["column-rule-width"];
		"columnSpan": RealProperties["column-span"];
		"columnWidth": RealProperties["column-width"];
		"columns": RealProperties["columns"];
		"contain": RealProperties["contain"];
		"containIntrinsicBlockSize": RealProperties["contain-intrinsic-block-size"];
		"containIntrinsicHeight": RealProperties["contain-intrinsic-height"];
		"containIntrinsicInlineSize": RealProperties["contain-intrinsic-inline-size"];
		"containIntrinsicSize": RealProperties["contain-intrinsic-size"];
		"containIntrinsicWidth": RealProperties["contain-intrinsic-width"];
		"content": RealProperties["content"];
		"contentVisibility": RealProperties["content-visibility"];
		"counterIncrement": RealProperties["counter-increment"];
		"counterReset": RealProperties["counter-reset"];
		"counterSet": RealProperties["counter-set"];
		"cursor": RealProperties["cursor"];
		"direction": RealProperties["direction"];
		"display": RealProperties["display"];
		"emptyCells": RealProperties["empty-cells"];
		"filter": RealProperties["filter"];
		"flex": RealProperties["flex"];
		"flexBasis": RealProperties["flex-basis"];
		"flexDirection": RealProperties["flex-direction"];
		"flexFlow": RealProperties["flex-flow"];
		"flexGrow": RealProperties["flex-grow"];
		"flexShrink": RealProperties["flex-shrink"];
		"flexWrap": RealProperties["flex-wrap"];
		"float": RealProperties["float"];
		"font": RealProperties["font"];
		"fontFamily": RealProperties["font-family"];
		"fontFeatureSettings": RealProperties["font-feature-settings"];
		"fontKerning": RealProperties["font-kerning"];
		"fontLanguageOverride": RealProperties["font-language-override"];
		"fontOpticalSizing": RealProperties["font-optical-sizing"];
		"fontSize": RealProperties["font-size"];
		"fontSizeAdjust": RealProperties["font-size-adjust"];
		"fontStretch": RealProperties["font-stretch"];
		"fontStyle": RealProperties["font-style"];
		"fontSynthesis": RealProperties["font-synthesis"];
		"fontVariant": RealProperties["font-variant"];
		"fontVariantAlternates": RealProperties["font-variant-alternates"];
		"fontVariantCaps": RealProperties["font-variant-caps"];
		"fontVariantEastAsian": RealProperties["font-variant-east-asian"];
		"fontVariantLigatures": RealProperties["font-variant-ligatures"];
		"fontVariantNumeric": RealProperties["font-variant-numeric"];
		"fontVariantPosition": RealProperties["font-variant-position"];
		"fontVariationSettings": RealProperties["font-variation-settings"];
		"fontWeight": RealProperties["font-weight"];
		"forcedColorAdjust": RealProperties["forced-color-adjust"];
		"gap": RealProperties["gap"];
		"grid": RealProperties["grid"];
		"gridArea": RealProperties["grid-area"];
		"gridAutoColumns": RealProperties["grid-auto-columns"];
		"gridAutoFlow": RealProperties["grid-auto-flow"];
		"gridAutoRows": RealProperties["grid-auto-rows"];
		"gridColumn": RealProperties["grid-column"];
		"gridColumnEnd": RealProperties["grid-column-end"];
		"gridColumnStart": RealProperties["grid-column-start"];
		"gridRow": RealProperties["grid-row"];
		"gridRowEnd": RealProperties["grid-row-end"];
		"gridRowStart": RealProperties["grid-row-start"];
		"gridTemplate": RealProperties["grid-template"];
		"gridTemplateAreas": RealProperties["grid-template-areas"];
		"gridTemplateColumns": RealProperties["grid-template-columns"];
		"gridTemplateRows": RealProperties["grid-template-rows"];
		"hangingPunctuation": RealProperties["hanging-punctuation"];
		"height": RealProperties["height"];
		"hyphenateCharacter": RealProperties["hyphenate-character"];
		"hyphens": RealProperties["hyphens"];
		"imageOrientation": RealProperties["image-orientation"];
		"imageRendering": RealProperties["image-rendering"];
		"imageResolution": RealProperties["image-resolution"];
		"imeMode": RealProperties["ime-mode"];
		"initialLetter": RealProperties["initial-letter"];
		"initialLetterAlign": RealProperties["initial-letter-align"];
		"inlineSize": RealProperties["inline-size"];
		"inset": RealProperties["inset"];
		"insetBlock": RealProperties["inset-block"];
		"insetBlockEnd": RealProperties["inset-block-end"];
		"insetBlockStart": RealProperties["inset-block-start"];
		"insetInline": RealProperties["inset-inline"];
		"insetInlineEnd": RealProperties["inset-inline-end"];
		"insetInlineStart": RealProperties["inset-inline-start"];
		"isolation": RealProperties["isolation"];
		"justifyContent": RealProperties["justify-content"];
		"justifyItems": RealProperties["justify-items"];
		"justifySelf": RealProperties["justify-self"];
		"justifyTracks": RealProperties["justify-tracks"];
		"left": RealProperties["left"];
		"letterSpacing": RealProperties["letter-spacing"];
		"lineBreak": RealProperties["line-break"];
		"lineHeight": RealProperties["line-height"];
		"lineHeightStep": RealProperties["line-height-step"];
		"listStyle": RealProperties["list-style"];
		"listStyleImage": RealProperties["list-style-image"];
		"listStylePosition": RealProperties["list-style-position"];
		"listStyleType": RealProperties["list-style-type"];
		"margin": RealProperties["margin"];
		"marginBlock": RealProperties["margin-block"];
		"marginBlockEnd": RealProperties["margin-block-end"];
		"marginBlockStart": RealProperties["margin-block-start"];
		"marginBottom": RealProperties["margin-bottom"];
		"marginInline": RealProperties["margin-inline"];
		"marginInlineEnd": RealProperties["margin-inline-end"];
		"marginInlineStart": RealProperties["margin-inline-start"];
		"marginLeft": RealProperties["margin-left"];
		"marginRight": RealProperties["margin-right"];
		"marginTop": RealProperties["margin-top"];
		"marginTrim": RealProperties["margin-trim"];
		"mask": RealProperties["mask"];
		"maskBorder": RealProperties["mask-border"];
		"maskBorderMode": RealProperties["mask-border-mode"];
		"maskBorderOutset": RealProperties["mask-border-outset"];
		"maskBorderRepeat": RealProperties["mask-border-repeat"];
		"maskBorderSlice": RealProperties["mask-border-slice"];
		"maskBorderSource": RealProperties["mask-border-source"];
		"maskBorderWidth": RealProperties["mask-border-width"];
		"maskClip": RealProperties["mask-clip"];
		"maskComposite": RealProperties["mask-composite"];
		"maskImage": RealProperties["mask-image"];
		"maskMode": RealProperties["mask-mode"];
		"maskOrigin": RealProperties["mask-origin"];
		"maskPosition": RealProperties["mask-position"];
		"maskRepeat": RealProperties["mask-repeat"];
		"maskSize": RealProperties["mask-size"];
		"maskType": RealProperties["mask-type"];
		"masonryAutoFlow": RealProperties["masonry-auto-flow"];
		"mathDepth": RealProperties["math-depth"];
		"mathShift": RealProperties["math-shift"];
		"mathStyle": RealProperties["math-style"];
		"maxBlockSize": RealProperties["max-block-size"];
		"maxHeight": RealProperties["max-height"];
		"maxInlineSize": RealProperties["max-inline-size"];
		"maxWidth": RealProperties["max-width"];
		"minBlockSize": RealProperties["min-block-size"];
		"minHeight": RealProperties["min-height"];
		"minInlineSize": RealProperties["min-inline-size"];
		"minWidth": RealProperties["min-width"];
		"mixBlendMode": RealProperties["mix-blend-mode"];
		"objectFit": RealProperties["object-fit"];
		"objectPosition": RealProperties["object-position"];
		"offset": RealProperties["offset"];
		"offsetAnchor": RealProperties["offset-anchor"];
		"offsetDistance": RealProperties["offset-distance"];
		"offsetPath": RealProperties["offset-path"];
		"offsetPosition": RealProperties["offset-position"];
		"offsetRotate": RealProperties["offset-rotate"];
		"opacity": RealProperties["opacity"];
		"order": RealProperties["order"];
		"orphans": RealProperties["orphans"];
		"outline": RealProperties["outline"];
		"outlineColor": RealProperties["outline-color"];
		"outlineOffset": RealProperties["outline-offset"];
		"outlineStyle": RealProperties["outline-style"];
		"outlineWidth": RealProperties["outline-width"];
		"overflow": RealProperties["overflow"];
		"overflowAnchor": RealProperties["overflow-anchor"];
		"overflowBlock": RealProperties["overflow-block"];
		"overflowClipMargin": RealProperties["overflow-clip-margin"];
		"overflowInline": RealProperties["overflow-inline"];
		"overflowWrap": RealProperties["overflow-wrap"];
		"overflowX": RealProperties["overflow-x"];
		"overflowY": RealProperties["overflow-y"];
		"overscrollBehavior": RealProperties["overscroll-behavior"];
		"overscrollBehaviorBlock": RealProperties["overscroll-behavior-block"];
		"overscrollBehaviorInline": RealProperties["overscroll-behavior-inline"];
		"overscrollBehaviorX": RealProperties["overscroll-behavior-x"];
		"overscrollBehaviorY": RealProperties["overscroll-behavior-y"];
		"padding": RealProperties["padding"];
		"paddingBlock": RealProperties["padding-block"];
		"paddingBlockEnd": RealProperties["padding-block-end"];
		"paddingBlockStart": RealProperties["padding-block-start"];
		"paddingBottom": RealProperties["padding-bottom"];
		"paddingInline": RealProperties["padding-inline"];
		"paddingInlineEnd": RealProperties["padding-inline-end"];
		"paddingInlineStart": RealProperties["padding-inline-start"];
		"paddingLeft": RealProperties["padding-left"];
		"paddingRight": RealProperties["padding-right"];
		"paddingTop": RealProperties["padding-top"];
		"pageBreakAfter": RealProperties["page-break-after"];
		"pageBreakBefore": RealProperties["page-break-before"];
		"pageBreakInside": RealProperties["page-break-inside"];
		"paintOrder": RealProperties["paint-order"];
		"perspective": RealProperties["perspective"];
		"perspectiveOrigin": RealProperties["perspective-origin"];
		"placeContent": RealProperties["place-content"];
		"placeItems": RealProperties["place-items"];
		"placeSelf": RealProperties["place-self"];
		"pointerEvents": RealProperties["pointer-events"];
		"position": RealProperties["position"];
		"printColorAdjust": RealProperties["print-color-adjust"];
		"quotes": RealProperties["quotes"];
		"resize": RealProperties["resize"];
		"right": RealProperties["right"];
		"rotate": RealProperties["rotate"];
		"rowGap": RealProperties["row-gap"];
		"rubyAlign": RealProperties["ruby-align"];
		"rubyPosition": RealProperties["ruby-position"];
		"scale": RealProperties["scale"];
		"scrollBehavior": RealProperties["scroll-behavior"];
		"scrollMargin": RealProperties["scroll-margin"];
		"scrollMarginBlock": RealProperties["scroll-margin-block"];
		"scrollMarginBlockEnd": RealProperties["scroll-margin-block-end"];
		"scrollMarginBlockStart": RealProperties["scroll-margin-block-start"];
		"scrollMarginBottom": RealProperties["scroll-margin-bottom"];
		"scrollMarginInline": RealProperties["scroll-margin-inline"];
		"scrollMarginInlineEnd": RealProperties["scroll-margin-inline-end"];
		"scrollMarginInlineStart": RealProperties["scroll-margin-inline-start"];
		"scrollMarginLeft": RealProperties["scroll-margin-left"];
		"scrollMarginRight": RealProperties["scroll-margin-right"];
		"scrollMarginTop": RealProperties["scroll-margin-top"];
		"scrollPadding": RealProperties["scroll-padding"];
		"scrollPaddingBlock": RealProperties["scroll-padding-block"];
		"scrollPaddingBlockEnd": RealProperties["scroll-padding-block-end"];
		"scrollPaddingBlockStart": RealProperties["scroll-padding-block-start"];
		"scrollPaddingBottom": RealProperties["scroll-padding-bottom"];
		"scrollPaddingInline": RealProperties["scroll-padding-inline"];
		"scrollPaddingInlineEnd": RealProperties["scroll-padding-inline-end"];
		"scrollPaddingInlineStart": RealProperties["scroll-padding-inline-start"];
		"scrollPaddingLeft": RealProperties["scroll-padding-left"];
		"scrollPaddingRight": RealProperties["scroll-padding-right"];
		"scrollPaddingTop": RealProperties["scroll-padding-top"];
		"scrollSnapAlign": RealProperties["scroll-snap-align"];
		"scrollSnapStop": RealProperties["scroll-snap-stop"];
		"scrollSnapType": RealProperties["scroll-snap-type"];
		"scrollTimeline": RealProperties["scroll-timeline"];
		"scrollTimelineAxis": RealProperties["scroll-timeline-axis"];
		"scrollTimelineName": RealProperties["scroll-timeline-name"];
		"scrollbarColor": RealProperties["scrollbar-color"];
		"scrollbarGutter": RealProperties["scrollbar-gutter"];
		"scrollbarWidth": RealProperties["scrollbar-width"];
		"shapeImageThreshold": RealProperties["shape-image-threshold"];
		"shapeMargin": RealProperties["shape-margin"];
		"shapeOutside": RealProperties["shape-outside"];
		"tabSize": RealProperties["tab-size"];
		"tableLayout": RealProperties["table-layout"];
		"textAlign": RealProperties["text-align"];
		"textAlignLast": RealProperties["text-align-last"];
		"textCombineUpright": RealProperties["text-combine-upright"];
		"textDecoration": RealProperties["text-decoration"];
		"textDecorationColor": RealProperties["text-decoration-color"];
		"textDecorationLine": RealProperties["text-decoration-line"];
		"textDecorationSkip": RealProperties["text-decoration-skip"];
		"textDecorationSkipInk": RealProperties["text-decoration-skip-ink"];
		"textDecorationStyle": RealProperties["text-decoration-style"];
		"textDecorationThickness": RealProperties["text-decoration-thickness"];
		"textEmphasis": RealProperties["text-emphasis"];
		"textEmphasisColor": RealProperties["text-emphasis-color"];
		"textEmphasisPosition": RealProperties["text-emphasis-position"];
		"textEmphasisStyle": RealProperties["text-emphasis-style"];
		"textIndent": RealProperties["text-indent"];
		"textJustify": RealProperties["text-justify"];
		"textOrientation": RealProperties["text-orientation"];
		"textOverflow": RealProperties["text-overflow"];
		"textRendering": RealProperties["text-rendering"];
		"textShadow": RealProperties["text-shadow"];
		"textSizeAdjust": RealProperties["text-size-adjust"];
		"textTransform": RealProperties["text-transform"];
		"textUnderlineOffset": RealProperties["text-underline-offset"];
		"textUnderlinePosition": RealProperties["text-underline-position"];
		"top": RealProperties["top"];
		"touchAction": RealProperties["touch-action"];
		"transform": RealProperties["transform"];
		"transformBox": RealProperties["transform-box"];
		"transformOrigin": RealProperties["transform-origin"];
		"transformStyle": RealProperties["transform-style"];
		"transition": RealProperties["transition"];
		"transitionDelay": RealProperties["transition-delay"];
		"transitionDuration": RealProperties["transition-duration"];
		"transitionProperty": RealProperties["transition-property"];
		"transitionTimingFunction": RealProperties["transition-timing-function"];
		"translate": RealProperties["translate"];
		"unicodeBidi": RealProperties["unicode-bidi"];
		"userSelect": RealProperties["user-select"];
		"verticalAlign": RealProperties["vertical-align"];
		"visibility": RealProperties["visibility"];
		"whiteSpace": RealProperties["white-space"];
		"widows": RealProperties["widows"];
		"width": RealProperties["width"];
		"willChange": RealProperties["will-change"];
		"wordBreak": RealProperties["word-break"];
		"wordSpacing": RealProperties["word-spacing"];
		"writingMode": RealProperties["writing-mode"];
		"zIndex": RealProperties["z-index"];
	}

	export type RealProperties = Merge<{
		"-moz-appearance": RealProperties["appearance"] | VendorAppearanceProperty;
		"-webkit-appearance": RealProperties["appearance"] | VendorAppearanceProperty;
		"-webkit-line-clamp": "none" | number;
		"-webkit-text-fill-color": Color;
		"-webkit-text-stroke": `${RealProperties["-webkit-text-stroke-width"]} ${RealProperties["-webkit-text-stroke-color"]}`;
		"-webkit-text-stroke-color": Color;
		"-webkit-text-stroke-width": "thin" | "medium" | "thick" | Length;
		"accent-color": "auto" | Color;
		"align-content": "normal" | BaselinePosition | ContentDistribution | OverflowPosition<ContentPosition> | ContentPosition;
		"align-items": "normal" | "stretch" | BaselinePosition | OverflowPosition<SelfPosition> | SelfPosition;
		"align-self": "auto" | "normal" | "stretch" | BaselinePosition | OverflowPosition<SelfPosition> | SelfPosition;
		"align-tracks": "normal" | BaselinePosition | ContentDistribution | OverflowPosition<ContentPosition> | ContentPosition;
		"all": GlobalValue;
		"animation": string;
		"animation-composition": Arrayize<"replace" | "add" | "accumulate">;
		"animation-delay": Arrayize<Time | `${Time} ${Time}`>;
		"animation-direction": Arrayize<"normal" | "reverse" | "alternate" | "alternate-reverse">;
		"animation-duration": Arrayize<Time>;
		"animation-fill-mode": Arrayize<"none" | "forwards" | "backwards" | "both">;
		"animation-iteration-count": Arrayize<"infinite" | number>;
		"animation-name": string;
		"animation-play-state": Arrayize<"running" | "paused">;
		"animation-timeline": string;
		"animation-timing-function": Arrayize<EasingFunction>;
		"appearance": "none" | "auto" | "searchfield" | "textarea" | "push-button" | "slider-horizontal" | "checkbox" | "radio" | "square-button" | "menulist" | "listbox" | "meter" | "progress-bar" | "button" | "textfield" | "menulist-button";
		"aspect-ratio": "auto" | Ratio;
		// TODO
		"backdrop-filter": any;
		// TODO
		"backface-visibility": any;
		// TODO
		"background": any;
		// TODO
		"background-attachment": any;
		// TODO
		"background-blend-mode": any;
		// TODO
		"background-clip": any;
		// TODO
		"background-color": any;
		// TODO
		"background-image": any;
		// TODO
		"background-origin": any;
		// TODO
		"background-position": any;
		// TODO
		"background-position-x": any;
		// TODO
		"background-position-y": any;
		// TODO
		"background-repeat": any;
		// TODO
		"background-size": any;
		// TODO
		"block-size": any;
		// TODO
		"border": any;
		// TODO
		"border-block": any;
		// TODO
		"border-block-color": any;
		// TODO
		"border-block-end": any;
		// TODO
		"border-block-end-color": any;
		// TODO
		"border-block-end-style": any;
		// TODO
		"border-block-end-width": any;
		// TODO
		"border-block-start": any;
		// TODO
		"border-block-start-color": any;
		// TODO
		"border-block-start-style": any;
		// TODO
		"border-block-start-width": any;
		// TODO
		"border-block-style": any;
		// TODO
		"border-block-width": any;
		// TODO
		"border-bottom": any;
		// TODO
		"border-bottom-color": any;
		// TODO
		"border-bottom-left-radius": any;
		// TODO
		"border-bottom-right-radius": any;
		// TODO
		"border-bottom-style": any;
		// TODO
		"border-bottom-width": any;
		// TODO
		"border-collapse": any;
		// TODO
		"border-color": any;
		// TODO
		"border-end-end-radius": any;
		// TODO
		"border-end-start-radius": any;
		// TODO
		"border-image": any;
		// TODO
		"border-image-outset": any;
		// TODO
		"border-image-repeat": any;
		// TODO
		"border-image-slice": any;
		// TODO
		"border-image-source": any;
		// TODO
		"border-image-width": any;
		// TODO
		"border-inline": any;
		// TODO
		"border-inline-color": any;
		// TODO
		"border-inline-end": any;
		// TODO
		"border-inline-end-color": any;
		// TODO
		"border-inline-end-style": any;
		// TODO
		"border-inline-end-width": any;
		// TODO
		"border-inline-start": any;
		// TODO
		"border-inline-start-color": any;
		// TODO
		"border-inline-start-style": any;
		// TODO
		"border-inline-start-width": any;
		// TODO
		"border-inline-style": any;
		// TODO
		"border-inline-width": any;
		// TODO
		"border-left": any;
		// TODO
		"border-left-color": any;
		// TODO
		"border-left-style": any;
		// TODO
		"border-left-width": any;
		// TODO
		"border-radius": any;
		// TODO
		"border-right": any;
		// TODO
		"border-right-color": any;
		// TODO
		"border-right-style": any;
		// TODO
		"border-right-width": any;
		// TODO
		"border-spacing": any;
		// TODO
		"border-start-end-radius": any;
		// TODO
		"border-start-start-radius": any;
		// TODO
		"border-style": any;
		// TODO
		"border-top": any;
		// TODO
		"border-top-color": any;
		// TODO
		"border-top-left-radius": any;
		// TODO
		"border-top-right-radius": any;
		// TODO
		"border-top-style": any;
		// TODO
		"border-top-width": any;
		// TODO
		"border-width": any;
		// TODO
		"bottom": any;
		// TODO
		"box-decoration-break": any;
		// TODO
		"box-shadow": any;
		// TODO
		"box-sizing": any;
		// TODO
		"break-after": any;
		// TODO
		"break-before": any;
		// TODO
		"break-inside": any;
		// TODO
		"caption-side": any;
		// TODO
		"caret-color": any;
		// TODO
		"clear": any;
		// TODO
		"clip": any;
		// TODO
		"clip-path": any;
		// TODO
		"color": any;
		// TODO
		"color-scheme": any;
		// TODO
		"column-count": any;
		// TODO
		"column-fill": any;
		// TODO
		"column-gap": any;
		// TODO
		"column-rule": any;
		// TODO
		"column-rule-color": any;
		// TODO
		"column-rule-style": any;
		// TODO
		"column-rule-width": any;
		// TODO
		"column-span": any;
		// TODO
		"column-width": any;
		// TODO
		"columns": any;
		// TODO
		"contain": any;
		// TODO
		"contain-intrinsic-block-size": any;
		// TODO
		"contain-intrinsic-height": any;
		// TODO
		"contain-intrinsic-inline-size": any;
		// TODO
		"contain-intrinsic-size": any;
		// TODO
		"contain-intrinsic-width": any;
		// TODO
		"content": any;
		// TODO
		"content-visibility": any;
		// TODO
		"counter-increment": any;
		// TODO
		"counter-reset": any;
		// TODO
		"counter-set": any;
		// TODO
		"cursor": any;
		// TODO
		"direction": any;
		// TODO
		"display": any;
		// TODO
		"empty-cells": any;
		// TODO
		"filter": any;
		// TODO
		"flex": any;
		// TODO
		"flex-basis": any;
		// TODO
		"flex-direction": any;
		// TODO
		"flex-flow": any;
		// TODO
		"flex-grow": any;
		// TODO
		"flex-shrink": any;
		// TODO
		"flex-wrap": any;
		// TODO
		"float": any;
		// TODO
		"font": any;
		// TODO
		"font-family": any;
		// TODO
		"font-feature-settings": any;
		// TODO
		"font-kerning": any;
		// TODO
		"font-language-override": any;
		// TODO
		"font-optical-sizing": any;
		// TODO
		"font-size": any;
		// TODO
		"font-size-adjust": any;
		// TODO
		"font-stretch": any;
		// TODO
		"font-style": any;
		// TODO
		"font-synthesis": any;
		// TODO
		"font-variant": any;
		// TODO
		"font-variant-alternates": any;
		// TODO
		"font-variant-caps": any;
		// TODO
		"font-variant-east-asian": any;
		// TODO
		"font-variant-ligatures": any;
		// TODO
		"font-variant-numeric": any;
		// TODO
		"font-variant-position": any;
		// TODO
		"font-variation-settings": any;
		// TODO
		"font-weight": any;
		// TODO
		"forced-color-adjust": any;
		// TODO
		"gap": any;
		// TODO
		"grid": any;
		// TODO
		"grid-area": any;
		// TODO
		"grid-auto-columns": any;
		// TODO
		"grid-auto-flow": any;
		// TODO
		"grid-auto-rows": any;
		// TODO
		"grid-column": any;
		// TODO
		"grid-column-end": any;
		// TODO
		"grid-column-start": any;
		// TODO
		"grid-row": any;
		// TODO
		"grid-row-end": any;
		// TODO
		"grid-row-start": any;
		// TODO
		"grid-template": any;
		// TODO
		"grid-template-areas": any;
		// TODO
		"grid-template-columns": any;
		// TODO
		"grid-template-rows": any;
		// TODO
		"hanging-punctuation": any;
		// TODO
		"height": any;
		// TODO
		"hyphenate-character": any;
		// TODO
		"hyphens": any;
		// TODO
		"image-orientation": any;
		// TODO
		"image-rendering": any;
		// TODO
		"image-resolution": any;
		// TODO
		"ime-mode": any;
		// TODO
		"initial-letter": any;
		// TODO
		"initial-letter-align": any;
		// TODO
		"inline-size": any;
		// TODO
		"inset": any;
		// TODO
		"inset-block": any;
		// TODO
		"inset-block-end": any;
		// TODO
		"inset-block-start": any;
		// TODO
		"inset-inline": any;
		// TODO
		"inset-inline-end": any;
		// TODO
		"inset-inline-start": any;
		// TODO
		"isolation": any;
		// TODO
		"justify-content": any;
		// TODO
		"justify-items": any;
		// TODO
		"justify-self": any;
		// TODO
		"justify-tracks": any;
		// TODO
		"left": any;
		// TODO
		"letter-spacing": any;
		// TODO
		"line-break": any;
		// TODO
		"line-height": any;
		// TODO
		"line-height-step": any;
		// TODO
		"list-style": any;
		// TODO
		"list-style-image": any;
		// TODO
		"list-style-position": any;
		// TODO
		"list-style-type": any;
		// TODO
		"margin": any;
		// TODO
		"margin-block": any;
		// TODO
		"margin-block-end": any;
		// TODO
		"margin-block-start": any;
		// TODO
		"margin-bottom": any;
		// TODO
		"margin-inline": any;
		// TODO
		"margin-inline-end": any;
		// TODO
		"margin-inline-start": any;
		// TODO
		"margin-left": any;
		// TODO
		"margin-right": any;
		// TODO
		"margin-top": any;
		// TODO
		"margin-trim": any;
		// TODO
		"mask": any;
		// TODO
		"mask-border": any;
		// TODO
		"mask-border-mode": any;
		// TODO
		"mask-border-outset": any;
		// TODO
		"mask-border-repeat": any;
		// TODO
		"mask-border-slice": any;
		// TODO
		"mask-border-source": any;
		// TODO
		"mask-border-width": any;
		// TODO
		"mask-clip": any;
		// TODO
		"mask-composite": any;
		// TODO
		"mask-image": any;
		// TODO
		"mask-mode": any;
		// TODO
		"mask-origin": any;
		// TODO
		"mask-position": any;
		// TODO
		"mask-repeat": any;
		// TODO
		"mask-size": any;
		// TODO
		"mask-type": any;
		// TODO
		"masonry-auto-flow": any;
		// TODO
		"math-depth": any;
		// TODO
		"math-shift": any;
		// TODO
		"math-style": any;
		// TODO
		"max-block-size": any;
		// TODO
		"max-height": any;
		// TODO
		"max-inline-size": any;
		// TODO
		"max-width": any;
		// TODO
		"min-block-size": any;
		// TODO
		"min-height": any;
		// TODO
		"min-inline-size": any;
		// TODO
		"min-width": any;
		// TODO
		"mix-blend-mode": any;
		// TODO
		"object-fit": any;
		// TODO
		"object-position": any;
		// TODO
		"offset": any;
		// TODO
		"offset-anchor": any;
		// TODO
		"offset-distance": any;
		// TODO
		"offset-path": any;
		// TODO
		"offset-position": any;
		// TODO
		"offset-rotate": any;
		// TODO
		"opacity": any;
		// TODO
		"order": any;
		// TODO
		"orphans": any;
		// TODO
		"outline": any;
		// TODO
		"outline-color": any;
		// TODO
		"outline-offset": any;
		// TODO
		"outline-style": any;
		// TODO
		"outline-width": any;
		// TODO
		"overflow": any;
		// TODO
		"overflow-anchor": any;
		// TODO
		"overflow-block": any;
		// TODO
		"overflow-clip-margin": any;
		// TODO
		"overflow-inline": any;
		// TODO
		"overflow-wrap": any;
		// TODO
		"overflow-x": any;
		// TODO
		"overflow-y": any;
		// TODO
		"overscroll-behavior": any;
		// TODO
		"overscroll-behavior-block": any;
		// TODO
		"overscroll-behavior-inline": any;
		// TODO
		"overscroll-behavior-x": any;
		// TODO
		"overscroll-behavior-y": any;
		// TODO
		"padding": any;
		// TODO
		"padding-block": any;
		// TODO
		"padding-block-end": any;
		// TODO
		"padding-block-start": any;
		// TODO
		"padding-bottom": any;
		// TODO
		"padding-inline": any;
		// TODO
		"padding-inline-end": any;
		// TODO
		"padding-inline-start": any;
		// TODO
		"padding-left": any;
		// TODO
		"padding-right": any;
		// TODO
		"padding-top": any;
		// TODO
		"page-break-after": any;
		// TODO
		"page-break-before": any;
		// TODO
		"page-break-inside": any;
		// TODO
		"paint-order": any;
		// TODO
		"perspective": any;
		// TODO
		"perspective-origin": any;
		// TODO
		"place-content": any;
		// TODO
		"place-items": any;
		// TODO
		"place-self": any;
		// TODO
		"pointer-events": any;
		// TODO
		"position": any;
		// TODO
		"print-color-adjust": any;
		// TODO
		"quotes": any;
		// TODO
		"resize": any;
		// TODO
		"right": any;
		// TODO
		"rotate": any;
		// TODO
		"row-gap": any;
		// TODO
		"ruby-align": any;
		// TODO
		"ruby-position": any;
		// TODO
		"scale": any;
		// TODO
		"scroll-behavior": any;
		// TODO
		"scroll-margin": any;
		// TODO
		"scroll-margin-block": any;
		// TODO
		"scroll-margin-block-end": any;
		// TODO
		"scroll-margin-block-start": any;
		// TODO
		"scroll-margin-bottom": any;
		// TODO
		"scroll-margin-inline": any;
		// TODO
		"scroll-margin-inline-end": any;
		// TODO
		"scroll-margin-inline-start": any;
		// TODO
		"scroll-margin-left": any;
		// TODO
		"scroll-margin-right": any;
		// TODO
		"scroll-margin-top": any;
		// TODO
		"scroll-padding": any;
		// TODO
		"scroll-padding-block": any;
		// TODO
		"scroll-padding-block-end": any;
		// TODO
		"scroll-padding-block-start": any;
		// TODO
		"scroll-padding-bottom": any;
		// TODO
		"scroll-padding-inline": any;
		// TODO
		"scroll-padding-inline-end": any;
		// TODO
		"scroll-padding-inline-start": any;
		// TODO
		"scroll-padding-left": any;
		// TODO
		"scroll-padding-right": any;
		// TODO
		"scroll-padding-top": any;
		// TODO
		"scroll-snap-align": any;
		// TODO
		"scroll-snap-stop": any;
		// TODO
		"scroll-snap-type": any;
		// TODO
		"scroll-timeline": any;
		// TODO
		"scroll-timeline-axis": any;
		// TODO
		"scroll-timeline-name": any;
		// TODO
		"scrollbar-color": any;
		// TODO
		"scrollbar-gutter": any;
		// TODO
		"scrollbar-width": any;
		// TODO
		"shape-image-threshold": any;
		// TODO
		"shape-margin": any;
		// TODO
		"shape-outside": any;
		// TODO
		"tab-size": any;
		// TODO
		"table-layout": any;
		// TODO
		"text-align": any;
		// TODO
		"text-align-last": any;
		// TODO
		"text-combine-upright": any;
		// TODO
		"text-decoration": any;
		// TODO
		"text-decoration-color": any;
		// TODO
		"text-decoration-line": any;
		// TODO
		"text-decoration-skip": any;
		// TODO
		"text-decoration-skip-ink": any;
		// TODO
		"text-decoration-style": any;
		// TODO
		"text-decoration-thickness": any;
		// TODO
		"text-emphasis": any;
		// TODO
		"text-emphasis-color": any;
		// TODO
		"text-emphasis-position": any;
		// TODO
		"text-emphasis-style": any;
		// TODO
		"text-indent": any;
		// TODO
		"text-justify": any;
		// TODO
		"text-orientation": any;
		// TODO
		"text-overflow": any;
		// TODO
		"text-rendering": any;
		// TODO
		"text-shadow": any;
		// TODO
		"text-size-adjust": any;
		// TODO
		"text-transform": any;
		// TODO
		"text-underline-offset": any;
		// TODO
		"text-underline-position": any;
		// TODO
		"top": any;
		// TODO
		"touch-action": any;
		// TODO
		"transform": any;
		// TODO
		"transform-box": any;
		// TODO
		"transform-origin": any;
		// TODO
		"transform-style": any;
		// TODO
		"transition": any;
		// TODO
		"transition-delay": any;
		// TODO
		"transition-duration": any;
		// TODO
		"transition-property": any;
		// TODO
		"transition-timing-function": any;
		// TODO
		"translate": any;
		// TODO
		"unicode-bidi": any;
		// TODO
		"user-select": any;
		// TODO
		"vertical-align": any;
		// TODO
		"visibility": any;
		// TODO
		"white-space": any;
		// TODO
		"widows": any;
		// TODO
		"width": any;
		// TODO
		"will-change": any;
		// TODO
		"word-break": any;
		// TODO
		"word-spacing": any;
		// TODO
		"writing-mode": any;
		// TODO
		"z-index": any;
	}, GlobalValue>;

	export type SVGProperties = {
		"alignmentBaseline": RealSVGProperties["alignment-baseline"];
		"baselineShift": RealSVGProperties["baseline-shift"];
		"clip": RealSVGProperties["clip"];
		"clipPath": RealSVGProperties["clip-path"];
		"clipRule": RealSVGProperties["clip-rule"];
		"color": RealSVGProperties["color"];
		"colorInterpolation": RealSVGProperties["color-interpolation"];
		"colorInterpolationFilters": RealSVGProperties["color-interpolation-filters"];
		"colorProfile": RealSVGProperties["color-profile"];
		"colorRendering": RealSVGProperties["color-rendering"];
		"cursor": RealSVGProperties["cursor"];
		"d": RealSVGProperties["d"];
		"direction": RealSVGProperties["direction"];
		"display": RealSVGProperties["display"];
		"dominantBaseline": RealSVGProperties["dominant-baseline"];
		"enableBackground": RealSVGProperties["enable-background"];
		"fill": RealSVGProperties["fill"];
		"fillOpacity": RealSVGProperties["fill-opacity"];
		"fillRule": RealSVGProperties["fill-rule"];
		"filter": RealSVGProperties["filter"];
		"floodColor": RealSVGProperties["flood-color"];
		"floodOpacity": RealSVGProperties["flood-opacity"];
		"fontFamily": RealSVGProperties["font-family"];
		"fontSize": RealSVGProperties["font-size"];
		"fontSizeAdjust": RealSVGProperties["font-size-adjust"];
		"fontStretch": RealSVGProperties["font-stretch"];
		"fontStyle": RealSVGProperties["font-style"];
		"fontVariant": RealSVGProperties["font-variant"];
		"fontWeight": RealSVGProperties["font-weight"];
		"glyphOrientationHorizontal": RealSVGProperties["glyph-orientation-horizontal"];
		"glyphOrientationVertical": RealSVGProperties["glyph-orientation-vertical"];
		"imageRendering": RealSVGProperties["image-rendering"];
		"kerning": RealSVGProperties["kerning"];
		"letterSpacing": RealSVGProperties["letter-spacing"];
		"lightingColor": RealSVGProperties["lighting-color"];
		"markerEnd": RealSVGProperties["marker-end"];
		"markerMid": RealSVGProperties["marker-mid"];
		"markerStart": RealSVGProperties["marker-start"];
		"mask": RealSVGProperties["mask"];
		"opacity": RealSVGProperties["opacity"];
		"overflow": RealSVGProperties["overflow"];
		"pointerEvents": RealSVGProperties["pointer-events"];
		"shapeRendering": RealSVGProperties["shape-rendering"];
		"solidColor": RealSVGProperties["solid-color"];
		"solidOpacity": RealSVGProperties["solid-opacity"];
		"stopColor": RealSVGProperties["stop-color"];
		"stopOpacity": RealSVGProperties["stop-opacity"];
		"stroke": RealSVGProperties["stroke"];
		"strokeDasharray": RealSVGProperties["stroke-dasharray"];
		"strokeDashoffset": RealSVGProperties["stroke-dashoffset"];
		"strokeLinecap": RealSVGProperties["stroke-linecap"];
		"strokeLinejoin": RealSVGProperties["stroke-linejoin"];
		"strokeMiterlimit": RealSVGProperties["stroke-miterlimit"];
		"strokeOpacity": RealSVGProperties["stroke-opacity"];
		"strokeWidth": RealSVGProperties["stroke-width"];
		"textAnchor": RealSVGProperties["text-anchor"];
		"textDecoration": RealSVGProperties["text-decoration"];
		"textRendering": RealSVGProperties["text-rendering"];
		"transform": RealSVGProperties["transform"];
		"unicodeBidi": RealSVGProperties["unicode-bidi"];
		"vectorEffect": RealSVGProperties["vector-effect"];
		"visibility": RealSVGProperties["visibility"];
		"wordSpacing": RealSVGProperties["word-spacing"];
		"writingMode": RealSVGProperties["writing-mode"];
	}

	export type RealSVGProperties = {
		// TODO
		"alignment-baseline": any;
		// TODO
		"baseline-shift": any;
		// TODO
		"clip": any;
		// TODO
		"clip-path": any;
		// TODO
		"clip-rule": any;
		// TODO
		"color": any;
		// TODO
		"color-interpolation": any;
		// TODO
		"color-interpolation-filters": any;
		// TODO
		"color-profile": any;
		// TODO
		"color-rendering": any;
		// TODO
		"cursor": any;
		// TODO
		"d": any;
		// TODO
		"direction": any;
		// TODO
		"display": any;
		// TODO
		"dominant-baseline": any;
		// TODO
		"enable-background": any;
		// TODO
		"fill": any;
		// TODO
		"fill-opacity": any;
		// TODO
		"fill-rule": any;
		// TODO
		"filter": any;
		// TODO
		"flood-color": any;
		// TODO
		"flood-opacity": any;
		// TODO
		"font-family": any;
		// TODO
		"font-size": any;
		// TODO
		"font-size-adjust": any;
		// TODO
		"font-stretch": any;
		// TODO
		"font-style": any;
		// TODO
		"font-variant": any;
		// TODO
		"font-weight": any;
		// TODO
		"glyph-orientation-horizontal": any;
		// TODO
		"glyph-orientation-vertical": any;
		// TODO
		"image-rendering": any;
		// TODO
		"kerning": any;
		// TODO
		"letter-spacing": any;
		// TODO
		"lighting-color": any;
		// TODO
		"marker-end": any;
		// TODO
		"marker-mid": any;
		// TODO
		"marker-start": any;
		// TODO
		"mask": any;
		// TODO
		"opacity": any;
		// TODO
		"overflow": any;
		// TODO
		"pointer-events": any;
		// TODO
		"shape-rendering": any;
		// TODO
		"solid-color": any;
		// TODO
		"solid-opacity": any;
		// TODO
		"stop-color": any;
		// TODO
		"stop-opacity": any;
		// TODO
		"stroke": any;
		// TODO
		"stroke-dasharray": any;
		// TODO
		"stroke-dashoffset": any;
		// TODO
		"stroke-linecap": any;
		// TODO
		"stroke-linejoin": any;
		// TODO
		"stroke-miterlimit": any;
		// TODO
		"stroke-opacity": any;
		// TODO
		"stroke-width": any;
		// TODO
		"text-anchor": any;
		// TODO
		"text-decoration": any;
		// TODO
		"text-rendering": any;
		// TODO
		"transform": any;
		// TODO
		"unicode-bidi": any;
		// TODO
		"vector-effect": any;
		// TODO
		"visibility": any;
		// TODO
		"word-spacing": any;
		// TODO
		"writing-mode": any;
	}
	
	export type Angle = `${number}${"deg" | "grad" | "rad" | "turn" | "%"}`;

	export type BasicShape = `${"inset" | "circle" | "ellipse" | "polygon" | "path"}(${string})`; // TODO

	export type BlendMode = "normal" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "color-dodge" | "color-burn" | "hard-light" | "soft-light" | "difference" | "exclusion" | "hue" | "saturation" | "color" | "luminosity";

	export type Color = number | `#${string}` | "black" | "silver" | "gray" | "white" | "maroon" | "red" | "purple" | "fuchsia" | "green" | "lime" | "olive" | "yellow" | "navy" | "blue" | "teal" | "aqua" | "orange" | "aliceblue" | "antiquewhite" | "aquamarine" | "azure" | "beige" | "bisque" | "blanchedalmond" | "blueviolet" | "brown" | "burlywood" | "cadetblue" | "chartreuse" | "chocolate" | "coral" | "cornflowerblue" | "cornsilk" | "crimson" | "cyan" | "darkblue" | "darkcyan" | "darkgoldenrod" | "darkgray" | "darkgreen" | "darkgrey" | "darkkhaki" | "darkmagenta" | "darkolivegreen" | "darkorange" | "darkorchid" | "darkred" | "darksalmon" | "darkseagreen" | "darkslateblue" | "darkslategray" | "darkslategrey" | "darkturquoise" | "darkviolet" | "deeppink" | "deepskyblue" | "dimgray" | "dimgrey" | "dodgerblue" | "firebrick" | "floralwhite" | "forestgreen" | "gainsboro" | "ghostwhite" | "gold" | "goldenrod" | "greenyellow" | "grey" | "honeydew" | "hotpink" | "indianred" | "indigo" | "ivory" | "khaki" | "lavender" | "lavenderblush" | "lawngreen" | "lemonchiffon" | "lightblue" | "lightcoral" | "lightcyan" | "lightgoldenrodyellow" | "lightgray" | "lightgreen" | "lightgrey" | "lightpink" | "lightsalmon" | "lightseagreen" | "lightskyblue" | "lightslategray" | "lightslategrey" | "lightsteelblue" | "lightyellow" | "limegreen" | "linen" | "magenta" | "mediumaquamarine" | "mediumblue" | "mediumorchid" | "mediumpurple" | "mediumseagreen" | "mediumslateblue" | "mediumspringgreen" | "mediumturquoise" | "mediumvioletred" | "midnightblue" | "mintcream" | "mistyrose" | "moccasin" | "navajowhite" | "oldlace" | "olivedrab" | "orangered" | "orchid" | "palegoldenrod" | "palegreen" | "paleturquoise" | "palevioletred" | "papayawhip" | "peachpuff" | "peru" | "pink" | "plum" | "powderblue" | "rosybrown" | "royalblue" | "saddlebrown" | "salmon" | "sandybrown" | "seagreen" | "seashell" | "sienna" | "skyblue" | "slateblue" | "slategray" | "slategrey" | "snow" | "springgreen" | "steelblue" | "tan" | "thistle" | "tomato" | "transparent" | "turquoise" | "violet" | "wheat" | "whitesmoke" | "yellowgreen" | "rebeccapurple" | "transparent" | `${"rgb" | "rgba" | "hsl" | "hsla" | "hwb" | "lab" | "lch" | "oklab" | "oklch" | "color"}(${string})`; // TODO

	export type EasingFunction = "linear" | `linear(${string})` | "ease" | "ease-in" | "ease-out" | "ease-in-out" | `cubic-bezier(${number}, ${number}, ${number}, ${number})` | "step-start" | "step-end" | `steps(${number})` | `steps(${number}, ${"jump-start" | "jump-end" | "jump-none" | "jump-both" | "start" | "end"})`

	export type FilterFunction = `${"blur" | "brightness" | "contrast" | "drop-shadow" | "grayscale" | "hue-rotate" | "invert" | "opacity" | "sepia" | "saturate"}(${string})`; // TODO

	export type Frequency = `${number}${"Hz" | "kHz" | "%"}`;

	export type Length = `${number}${"cap" | "ch" | "em" | "ex" | "ic" | "lh" | "rem" | "rlh" | "vh" | "vw" | "vi" | "vb" | "vmin" | "vmax" | "px" | "cm" | "mm" | "Q" | "in" | "pc" | "pt" | "%"}`;

	export type Percentage = `${number}%`;

	export type Ratio = `${number}/${number}` | `${number} / ${number}`;

	export type Resolution = `${number}${"dpi" | "dpcm" | "dppx" | "x"}`;

	type TypeShape = `rect(${string})`; // TODO

	export type Time = `${number}${"s" | "ms" | "%"}`;
	// TODO
	type TypeTransformFunction = any;
	// TODO
	type TypeTranslationValue = any;

	export type URLFunction = `url(${string})`;

	type GlobalValue = "inherit" | "initial" | "unset" | "revert" | "revert-layer";

	type BaselinePosition = "baseline" | "first baseline" | "last baseline";

	type ContentDistribution = "space-between" | "space-around" | "space-evenly" | "stretch";

	type ContentPosition = "center" | "start" | "end" | "flex-start" | "flex-end";

	type SelfPosition = ContentPosition | "self-start" | "self-end";

	type OverflowPosition<T extends string> = `safe ${T}` | `unsafe ${T}`;

	type VendorAppearanceProperty = "attachment" | "borderless-attachment" | "button-bevel" | "caps-lock-indicator" | "caret" | "checkbox-container" | "checkbox-label" | "checkmenuitem" | "color-well" | "continuous-capacity-level-indicator" | "default-button" | "discrete-capacity-level-indicator" | "inner-spin-button" | "image-controls-button" | "list-button" | "listitem" | "media-enter-fullscreen-button" | "media-exit-fullscreen-button" | "media-fullscreen-volume-slider" | "media-fullscreen-volume-slider-thumb" | "media-mute-button" | "media-play-button" | "media-overlay-play-button" | "media-return-to-realtime-button" | "media-rewind-button" | "media-seek-back-button" | "media-seek-forward-button" | "media-toggle-closed-captions-button" | "media-slider" | "media-sliderthumb" | "media-volume-slider-container" | "media-volume-slider-mute-button" | "media-volume-slider" | "media-volume-sliderthumb" | "media-controls-background" | "media-controls-dark-bar-background" | "media-controls-fullscreen-background" | "media-controls-light-bar-background" | "media-current-time-display" | "media-time-remaining-display" | "menulist-text" | "menulist-textfield" | "meterbar" | "number-input" | "progress-bar-value" | "progressbar" | "progressbar-vertical" | "range" | "range-thumb" | "rating-level-indicator" | "relevancy-level-indicator" | "scale-horizontal" | "scalethumbend" | "scalethumb-horizontal" | "scalethumbstart" | "scalethumbtick" | "scalethumb-vertical" | "scale-vertical" | "scrollbarthumb-horizontal" | "scrollbarthumb-vertical" | "scrollbartrack-horizontal" | "scrollbartrack-vertical" | "searchfield-decoration" | "searchfield-results-decoration" | "searchfield-results-button" | "searchfield-cancel-button" | "snapshotted-plugin-overlay" | "sheet" | "slider-vertical" | "sliderthumb-horizontal" | "sliderthumb-vertical" | "textfield-multiline" | "-apple-pay-button";

	export module fn {

	}
}

type Merge<T extends object, U> = {
	[K in keyof T]: T[K] | U;
}

type Arrayize<T> = T | T[];
